version: "3.6"
services:
  svc:
    build: ./svc
    ports: 
      - "32379"
    environment:
      - PORT=32379
      - devmode=true
  web:
    build: ./web
    volumes:
      - ./web/static:/work/static
    ports:
      - "32379:80"
    depends_on: 
      - "svc"
