services:
  svc:
    build: ./svc
    ports: 
      - "%port%"
    environment:
      - PORT=%port%
      - devmode=true
    volumes:
      - ./svc/template:/work/template
  web:
    build: ./web
    volumes:
      - ./web/static:/work/static
    ports:
      - "%port%:80"
    depends_on: 
      - "svc"
